# Generated by Django 4.0 on 2022-06-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Required', max_length=255, verbose_name="Project's name")),
                ('description', models.TextField(help_text='Required', verbose_name="Project's description")),
                ('slug', models.SlugField(help_text='Required', max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name="Project's image")),
                ('project_date', models.DateField(help_text='Required', verbose_name='Date when the porject was created')),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
