# Generated by Django 4.0.5 on 2022-06-09 20:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='techologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Python'), (2, 'JavaScript'), (3, 'Html/Css'), (4, 'React'), (5, 'NextJs'), (6, 'Django'), (7, 'Postgresql'), (8, 'MySql'), (9, 'Graphql'), (10, 'Tensorflow/Keras'), (11, 'Numpy/Pandas/Matplotlib/Scikit-learn'), (12, 'Jupyter/JupyterLab')], default='none', max_length=26),
            preserve_default=False,
        ),
    ]
