# Generated by Django 4.0.5 on 2022-06-09 20:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_techologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='techologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Python'), (2, 'Javascript'), (3, 'Typescript'), (4, 'Html/Css'), (5, 'React'), (6, 'NextJs'), (7, 'Django'), (8, 'Postgresql'), (9, 'MySql'), (10, 'Graphql'), (11, 'Tensorflow/Keras'), (12, 'Numpy/Pandas/Matplotlib/Scikit-learn'), (13, 'Jupyter/JupyterLab')], max_length=29),
        ),
    ]
