# Generated by Django 4.0.5 on 2022-06-09 20:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_techologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='techologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Python'), (2, 'Javascript'), (3, 'Typescript'), (4, 'Html/Css'), (5, 'React'), (6, 'NextJs'), (7, 'TailwindCss'), (8, 'ChakraUI'), (9, 'MaterialUI'), (10, 'Bootstrap'), (11, 'Django'), (12, 'Postgresql'), (13, 'MySql'), (14, 'Graphql'), (15, 'Tensorflow/Keras'), (16, 'Numpy/Pandas/Matplotlib/Scikit-learn'), (17, 'Jupyter/JupyterLab')], max_length=41),
        ),
    ]
