# Generated by Django 4.0.5 on 2022-06-09 20:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_project_techologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='techologies',
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('Typescript', 'Typescript'), ('Html/Css', 'Html/Css'), ('React', 'React'), ('NextJs', 'NextJs'), ('TailwindCss', 'TailwindCss'), ('ChakraUI', 'ChakraUI'), ('MaterialUI', 'MaterialUI'), ('Bootstrap', 'Bootstrap'), ('Django/DRF', 'Django/DRF'), ('Postgresql', 'Postgresql'), ('MySql', 'MySql'), ('Graphql', 'Graphql'), ('Tensorflow/Keras', 'Tensorflow/Keras'), ('Numpy/Pandas/Matplotlib/Scikit-learn', 'Numpy/Pandas/Matplotlib/Scikit-learn'), ('Jupyter/JupyterLab', 'Jupyter/JupyterLab')], default='none', max_length=201),
            preserve_default=False,
        ),
    ]
