# Generated by Django 4.0.5 on 2022-06-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_project_techologies_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brief_description',
            field=models.CharField(help_text='Required', max_length=400, null=True, verbose_name='Brief description'),
        ),
    ]
