# Generated by Django 4.0.5 on 2022-06-14 00:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project_brief_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('Typescript', 'Typescript'), ('Html5', 'Html5'), ('Css3', 'Css3'), ('React', 'React'), ('NextJs', 'NextJs'), ('TailwindCss', 'TailwindCss'), ('MaterialUI', 'MaterialUI'), ('Bootstrap', 'Bootstrap'), ('Django/DRF', 'Django/DRF'), ('Sqlite', 'Sqlite'), ('Postgresql', 'Postgresql'), ('MySql', 'MySql'), ('Graphql', 'Graphql'), ('Anaconda', 'Anaconda'), ('Tensorflow', 'Tensorflow'), ('Numpy', 'Numpy'), ('Pandas', 'Pandas'), ('Jupyter', 'Jupyter'), ('Pytest', 'Pytest'), ('Selenium', 'Selenium'), ('Heroku', 'Heroku'), ('Ubuntu', 'Ubuntu'), ('Linux', 'Linux'), ('Vim', 'Vim'), ('Vscode', 'Vscode')], max_length=216),
        ),
    ]
