# Generated by Django 4.0.5 on 2022-06-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repo',
            field=models.URLField(blank=True),
        ),
    ]
